language: ruby
sudo: required
dist: trusty
os:
  - linux
services:
  - docker
script: |
  docker login -u=$DOCKER_USER -p=$DOCKER_PASS
  docker build -t synker/webgraboneshot:${TRAVIS_BUILD_NUMBER} -t synker/webgraboneshot:latest .
  docker push synker/webgraboneshot
notifications: # set notification options
  email:
    recipients:
      - tunisienheni@gmail.com
    on_success: change
    on_failure: change